edition = "2021"
array_width = 80
attr_fn_like_width = 80
chain_width = 80
comment_width = 100
fn_call_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
